services:
  backend:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
    networks:
      - manicel_network

  db:
    image: postgres:17.0
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - /home/sp28337/docker_volume/postgres:/var/lib/postgresql/data
    networks:
      - manicel_network

  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - manicel_network

networks:
  manicel_network: