[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Pavel Tarakanov <sp28337@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.4"
pydantic = "^2.9.2"
uvicorn = "^0.32.0"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.36"}
alembic = "^1.13.3"
httpx = "^0.27.2"
pydantic-settings = "^2.6.1"
psycopg2-binary = "^2.9.10"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
requests = "^2.32.3"
asyncpg = "^0.30.0"
greenlet = "^3.1.1"
gunicorn = "^23.0.0"
uvicorn-worker = "^0.2.0"
pytest = {extras = ["async"], version = "^8.3.3"}
pytest-asyncio = "^0.24.0"
pytest-trio = "^0.8.0"
pytest-twisted = "^1.14.3"
twisted = "^24.10.0"
pytest-factoryboy = "^2.7.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.11.8"
black = "^25.1.0"

[tool.ruff]
lint.ignore = ["F403"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "session"
# asyncio_mode = "strict"