"""add_yandex_access_token_column

Revision ID: 1897ce1cd424
Revises: a2caf7187593
Create Date: 2024-11-21 21:21:52.779811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1897ce1cd424'
down_revision: Union[str, None] = 'a2caf7187593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('yandex_access_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'yandex_access_token')
    # ### end Alembic commands ###
