"""username_and_password_in_user_mosels_nullable_true

Revision ID: 19a7013efeed
Revises: f30339ef33c3
Create Date: 2024-11-19 12:26:11.814819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a7013efeed'
down_revision: Union[str, None] = 'f30339ef33c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_profiles', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_profiles', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
