"""add_expiration_date_table

Revision ID: 307fc8f297a9
Revises: 78c713808fad
Create Date: 2025-04-11 08:53:58.646996

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "307fc8f297a9"
down_revision: Union[str, None] = "78c713808fad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
