"""add complectation table

Revision ID: 3a3db84d350e
Revises: b2648b37dccf
Create Date: 2025-05-06 15:02:04.736491

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3a3db84d350e"
down_revision: Union[str, None] = "b2648b37dccf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "complectations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column(
        "products", sa.Column("complectation_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "products", "complectations", ["complectation_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="foreignkey")
    op.drop_column("products", "complectation_id")
    op.drop_table("complectations")
    # ### end Alembic commands ###
