"""access_token_optional

Revision ID: 442ffccda541
Revises: 36eb1f082334
Create Date: 2024-11-15 19:00:41.130974

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "442ffccda541"
down_revision: Union[str, None] = "36eb1f082334"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_profiles", "access_token", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_profiles", "access_token", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
