"""rewievs_column

Revision ID: 74deefd07eae
Revises: 520d2cc7545a
Create Date: 2025-03-31 17:22:06.691065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74deefd07eae'
down_revision: Union[str, None] = '520d2cc7545a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('reviews', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'reviews')
    # ### end Alembic commands ###
