"""add_admin_column_to_users_profile

Revision ID: 75749f0270b5
Revises: ce2e1e9f8b3a
Create Date: 2024-11-18 14:35:36.852096

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75749f0270b5"
down_revision: Union[str, None] = "ce2e1e9f8b3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_profiles", sa.Column("admin", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profiles", "admin")
    # ### end Alembic commands ###
