"""add_volumes_and_product_volumes_tables

Revision ID: 78c713808fad
Revises: 7f488bde2e90
Create Date: 2025-04-10 18:13:39.665656

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78c713808fad"
down_revision: Union[str, None] = "7f488bde2e90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "volumes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("volume"),
    )
    op.create_table(
        "product_volumes",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("volume_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["volume_id"],
            ["volumes.id"],
        ),
        sa.PrimaryKeyConstraint("product_id", "volume_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_volumes")
    op.drop_table("volumes")
    # ### end Alembic commands ###
