"""fix-1

Revision ID: 7f488bde2e90
Revises: 74deefd07eae
Create Date: 2025-04-10 17:59:47.673481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f488bde2e90'
down_revision: Union[str, None] = '74deefd07eae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_volumes')
    op.drop_table('volumes')
    op.drop_constraint('products_effect_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'effect_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('effect_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_effect_id_fkey', 'products', 'effects', ['effect_id'], ['id'])
    op.create_table('volumes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('volumes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='volumes_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='volumes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('product_volumes',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('volume_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_volumes_product_id_fkey'),
    sa.ForeignKeyConstraint(['volume_id'], ['volumes.id'], name='product_volumes_volume_id_fkey'),
    sa.PrimaryKeyConstraint('product_id', 'volume_id', name='product_volumes_pkey')
    )
    # ### end Alembic commands ###
