"""add articule field to products table

Revision ID: 8db22e091694
Revises: 8fb8a749b33a
Create Date: 2025-04-12 13:50:26.663349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db22e091694'
down_revision: Union[str, None] = '8fb8a749b33a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('articule', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'articule')
    # ### end Alembic commands ###
