"""add note field to products table

Revision ID: 8fb8a749b33a
Revises: d44831d64a1f
Create Date: 2025-04-11 10:40:53.261667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb8a749b33a'
down_revision: Union[str, None] = 'd44831d64a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'note')
    # ### end Alembic commands ###
