"""fix_relationships

Revision ID: 90130bf62165
Revises: 141e62d905a5
Create Date: 2024-11-09 10:21:28.124732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90130bf62165'
down_revision: Union[str, None] = '141e62d905a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_flavors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_flavors',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('flavor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['flavor_id'], ['flavors.id'], name='product_flavors_flavor_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_flavors_product_id_fkey'),
    sa.PrimaryKeyConstraint('product_id', 'flavor_id', name='product_flavors_pkey')
    )
    # ### end Alembic commands ###
