"""add relationships

Revision ID: 98a3db975d6f
Revises: 9e161ac01b2d
Create Date: 2024-11-07 22:49:28.918009

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "98a3db975d6f"
down_revision: Union[str, None] = "9e161ac01b2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("flavor_id", sa.Integer(), nullable=True))
    op.drop_constraint("products_flavor_fkey", "products", type_="foreignkey")
    op.create_foreign_key(None, "products", "flavors", ["flavor_id"], ["id"])
    op.drop_column("products", "flavor")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("flavor", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "products", type_="foreignkey")
    op.create_foreign_key(
        "products_flavor_fkey", "products", "flavors", ["flavor"], ["id"]
    )
    op.drop_column("products", "flavor_id")
    # ### end Alembic commands ###
