"""add_flavor_column_to_Products

Revision ID: 9e161ac01b2d
Revises: e8ff44ae19d8
Create Date: 2024-11-07 20:26:17.592158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e161ac01b2d'
down_revision: Union[str, None] = 'e8ff44ae19d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('flavor', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'flavors', ['flavor'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'flavor')
    # ### end Alembic commands ###
