"""add name_ru column to Products table

Revision ID: b2648b37dccf
Revises: 3f5dfcb6ff7c
Create Date: 2025-04-24 17:56:24.926062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2648b37dccf'
down_revision: Union[str, None] = '3f5dfcb6ff7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name_ru', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'name_ru')
    # ### end Alembic commands ###
