"""set nullable=False to uid and status columns

Revision ID: bb7b3d24225a
Revises: efe89dbf8885
Create Date: 2025-05-25 17:28:24.502842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb7b3d24225a'
down_revision: Union[str, None] = 'efe89dbf8885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'uid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('products', 'status',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'status',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.alter_column('products', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('products', 'uid',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
