"""change fields in expiration date table

Revision ID: bee69fb0602c
Revises: 307fc8f297a9
Create Date: 2025-04-11 09:10:18.886427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee69fb0602c'
down_revision: Union[str, None] = '307fc8f297a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expiration_dates', sa.Column('before_opening', sa.String(), nullable=True))
    op.add_column('expiration_dates', sa.Column('after_opening', sa.String(), nullable=True))
    op.drop_column('expiration_dates', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expiration_dates', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('expiration_dates', 'after_opening')
    op.drop_column('expiration_dates', 'before_opening')
    # ### end Alembic commands ###
