"""m2m1

Revision ID: c5d0db801c63
Revises: d697139580d9
Create Date: 2024-11-14 11:30:44.531479

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "c5d0db801c63"
down_revision: Union[str, None] = "d697139580d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
