"""uid status created columns

Revision ID: efe89dbf8885
Revises: 3a3db84d350e
Create Date: 2025-05-25 10:24:56.371455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe89dbf8885'
down_revision: Union[str, None] = '3a3db84d350e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('uid', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('products', sa.Column('status', sa.Enum('AVAILABLE', 'UNAVAILABLE', 'LIMITED', 'PENDING', 'INACTIVE', 'DELETED', name='status', native_enum=False), nullable=True))
    op.create_foreign_key(None, 'products', 'user_profiles', ['uid'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'status')
    op.drop_column('products', 'created')
    op.drop_column('products', 'uid')
    # ### end Alembic commands ###
