"""extend_user_profile

Revision ID: f30339ef33c3
Revises: 5853611e0cfa
Create Date: 2024-11-19 11:59:37.461455

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f30339ef33c3"
down_revision: Union[str, None] = "5853611e0cfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_profiles", sa.Column("name", sa.String(), nullable=True))
    op.add_column(
        "user_profiles", sa.Column("google_access_token", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profiles", "google_access_token")
    op.drop_column("user_profiles", "name")
    # ### end Alembic commands ###
