"""change product table

Revision ID: fcdbcf365d90
Revises: 74deefd07eae
Create Date: 2025-04-08 08:53:52.572701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcdbcf365d90'
down_revision: Union[str, None] = '74deefd07eae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'attention',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'attention',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
