name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.12"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ hashFiles('poetry.lock') }}

      - run: |
          pip install poetry
          poetry install --no-root

      - run: poetry run black app --check
      - run: poetry run ruff check app

  tests:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.12"

      - run: |
          pip install poetry
          poetry install --no-root

      - run: docker compose -f docker-compose.test.yml up -d
      - run: poetry run pytest tests/unit
      - run: docker compose down -v

  deploy:
    needs: tests
    runs-on: ubuntu-latest
    environment: manicel

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |       
          cd ~/manicel/backend &&
          export PATH="~/.local/bin/poetry" ;
          export PATH="~/.local/bin:/usr/local/bin:/usr/bin:/bin:$PATH" ;
          git switch main ;
          echo '=== Restarting service ===' &&
          sudo systemctl daemon-reload &&
          sudo systemctl stop manicel-backend.service &&
          git pull &&
          sudo systemctl start manicel-backend.service &&
          echo '=== Verifying service ===' &&
          sudo systemctl status manicel-backend.service
          echo "✅ Deployment successful!"